# App
spring.application.name=recommendation-service
server.port=8083

# MongoDB
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=resumedb

# Kafka
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=recommendation-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

# Ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=llama3
spring.ai.ollama.embedding.options.model=nomic-embed-text


# Chroma
spring.ai.vectorstore.chroma.client.host=localhost
spring.ai.vectorstore.chroma.client.port=8000
spring.ai.vectorstore.chroma.collection-name=job-descriptions
spring.ai.vectorstore.chroma.initialize-schema=true
spring.ai.vectorstore.chroma.tenant=default_tenant
spring.ai.vectorstore.chroma.database=default_database


logging.level.org.springframework.ai=TRACE
logging.level.org.springframework.web.client=TRACE
logging.level.org.springframework.http=TRACE
logging.level.org.springframework.web=TRACE
logging.level.org.springframework.ai.chroma=TRACE